version: "3.4"

services:
  app:
    image: todo-in-rust
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=/app/db/test.db
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - database-file:/app/db

volumes:
  database-file: