name: ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: whitehattux/todo-in-rust-be:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  docker-armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch cargo cross
        run: cargo install cross
      - name: Build
        run: cross build --target armv7-unknown-linux-gnueabihf --release
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.armv7
          push: true
          tags: whitehattux/todo-in-rust-be:latest-arm
